/* Write a function named divide that takes two parameters a and b and returns the result of dividing a by b. 
Handle the case where b is 0 gracefully by throwing an appropriate error message.*/

// Error Handling with a Logical Error

try {
  let x = 10 / 0; // This will throw a "Division by zero" error
} catch (error) {
    if (error instanceof TypeError) {
    console.log("TypeError occurred: ", error.message);
  } else if (error instanceof ReferenceError) {
    console.log("ReferenceError occurred: ", error.message);
  } else if (error instanceof RangeError) {
    console.log("RangeError occurred: ", error.message);
  } else {
    console.log("An error occurred: ", error.message);
  }
}
